/* Generated By:JavaCC: Do not edit this line. Parser.java */
package parser;

import java.util.Vector;

import experiment.ActionAppearance;
import experiment.CyclicAppearance;
import experiment.ProbabilisticAppearance;
import experiment.Rule;
import experiment.SingleAppearance;
import experiment.Action;
import experiment.ZoneCommand;
import distribution.ZoneDistribution;
import distribution.GenotypeAgeCountTrio;
import genotype.Genotype;

public class Parser implements ParserConstants {
    public Vector<Rule> readRules(){
      try{
               return ruleList();
          }
          catch(Exception e){
               e.printStackTrace();
          }
          return null;
    }

//=======================| RULE LIST   static final public Vector<Rule> ruleList() throws ParseException {
    Vector<Rule> rules = new Vector<Rule>();
    Rule curRule;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EVERY:
      case IN:
      case WITH_POSSIBILITY:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      curRule = rule();
         rules.add(curRule);
    }
     {if (true) return rules;}
    throw new Error("Missing return statement in function");
  }

 //^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//=======================| RULE 
  static final public Rule rule() throws ParseException {
     Rule rule;
    ActionAppearance actionAppearance;
    Vector<Action> actions;
    int from = Rule.FOREVER_BEFORE,
        to = Rule.FOREVER_AFTER;
    Token token;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IN:
      jj_consume_token(IN);
      token = jj_consume_token(NUMBER);
             from = Integer.parseInt(token.image);
             actionAppearance =
             new SingleAppearance(from);
             to = from;
      break;
    case EVERY:
    case WITH_POSSIBILITY:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EVERY:
        jj_consume_token(EVERY);
        token = jj_consume_token(NUMBER);
               actionAppearance =
              new CyclicAppearance(Float.parseFloat(token.image));
        break;
      case WITH_POSSIBILITY:
        jj_consume_token(WITH_POSSIBILITY);
        token = jj_consume_token(NUMBER);
               actionAppearance =
              new ProbabilisticAppearance(Float.parseFloat(token.image));
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FROM:
        jj_consume_token(FROM);
        token = jj_consume_token(NUMBER);
         from=Integer.parseInt(token.image);
        break;
      default:
        jj_la1[2] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TO:
        jj_consume_token(TO);
        token = jj_consume_token(NUMBER);
         to=Integer.parseInt(token.image);
        break;
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    actions = actionList();
   {if (true) return new Rule(actionAppearance, actions, from, to);}
    throw new Error("Missing return statement in function");
  }

 //^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//=======================| ACTION LIST  static final public Vector<Action> actionList() throws ParseException {
    Vector<Action> actions = new Vector<Action>();
    Action curAction;
    label_2:
    while (true) {
      curAction = action();
         actions.add(curAction);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FOR:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_2;
      }
    }
     {if (true) return actions;}
    throw new Error("Missing return statement in function");
  }

 //^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//=======================| ACTION  static final public Action action() throws ParseException {
    Action action;
   Vector<Integer> zones = new Vector<Integer>();
   ZoneDistribution zoneDistribution = new ZoneDistribution();
   ZoneCommand command;
   Token tokenG, tokenA, tokenN, token;
    jj_consume_token(FOR);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMBER:
      label_3:
      while (true) {
        token = jj_consume_token(NUMBER);
          zones.add(Integer.parseInt(token.image));
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NUMBER:
          ;
          break;
        default:
          jj_la1[6] = jj_gen;
          break label_3;
        }
      }
      break;
    case EACH:
      jj_consume_token(EACH);
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(IMMIGRATION);
    label_4:
    while (true) {
      tokenG = jj_consume_token(GENOTYPE);
      tokenA = jj_consume_token(NUMBER);
      tokenN = jj_consume_token(NUMBER);
           zoneDistribution.addGenotypeDistribution(
                                new GenotypeAgeCountTrio(
                                        Genotype.getGenotype(tokenG.image),
                                        Integer.parseInt(tokenA.image),
                                        Integer.parseInt(tokenN.image)));
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 21:
      case 22:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 21:
          jj_consume_token(21);
          break;
        case 22:
          jj_consume_token(22);
          break;
        default:
          jj_la1[8] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[9] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case GENOTYPE:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_4;
      }
    }
     {if (true) return new Action(
                    zones,
                    new ZoneCommand(
                                ZoneCommand.Type.ADD_INDIVIDUALS,
                                zoneDistribution));}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public ParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[11];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xc80,0x880,0x100,0x200,0xc80,0x1000,0x80000,0x82000,0x600000,0x600000,0x10000,};
   }

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 11; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 11; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 11; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 11; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 11; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 11; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[23];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 11; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 23; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
