/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EVERY = 7;
  /** RegularExpression Id. */
  int FROM = 8;
  /** RegularExpression Id. */
  int TO = 9;
  /** RegularExpression Id. */
  int IN = 10;
  /** RegularExpression Id. */
  int WITH_POSSIBILITY = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int EACH = 13;
  /** RegularExpression Id. */
  int IMMIGRATION = 14;
  /** RegularExpression Id. */
  int ABSOLUTE = 15;
  /** RegularExpression Id. */
  int GENOTYPE = 16;
  /** RegularExpression Id. */
  int SPECIES = 17;
  /** RegularExpression Id. */
  int GENDER = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"every\"",
    "\"from\"",
    "\"to\"",
    "\"in\"",
    "\"with possibility\"",
    "\"for\"",
    "\"each\"",
    "\"immigration\"",
    "\"absolute\"",
    "<GENOTYPE>",
    "<SPECIES>",
    "<GENDER>",
    "<NUMBER>",
    "<DIGIT>",
    "\",\"",
    "\";\"",
  };

}
