/* Generated By:JavaCC: Do not edit this line. ParserTokenManager.java */
package utils.parser;
import java.util.List;
import java.util.LinkedList;
import distribution.GenotypeAgeCountTrio;
import distribution.ZoneDistribution;
import experiment.scenario.Action;
import experiment.scenario.repeaters.ActionRepeat;
import experiment.scenario.repeaters.CyclicRepeat;
import experiment.scenario.repeaters.ProbabilisticRepeat;
import experiment.scenario.Rule;
import experiment.scenario.repeaters.SingleRepeat;
import experiment.scenario.ZoneCommand;
import experiment.individual.genotype.Genotype;
import statistic.StatisticSettings;
import statistic.StatisticSettings.Subiteration;

/** Token Manager. */
public class ParserTokenManager implements ParserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 44:
         return jjStopAtPos(0, 32);
      case 59:
         return jjStopAtPos(0, 17);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0xfc408000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x2080L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x1100L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x4400L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x200L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_0(0x3000800L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa2_0(active0, 0xfc000000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x3000800L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
      case 78:
      case 110:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(1, 10);
         break;
      case 79:
      case 111:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(1, 9);
         return jjMoveStringLiteralDfa2_0(active0, 0x1000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x100L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x400080L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L);
      case 82:
      case 114:
         if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(2, 12);
         break;
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0xff000800L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0xfc000000L);
      case 72:
      case 104:
         if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(3, 13);
         return jjMoveStringLiteralDfa4_0(active0, 0x3000800L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 77:
      case 109:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(3, 8);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x808000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x80L);
      case 83:
      case 115:
         if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(3, 22);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa5_0(active0, 0x800L);
      case 95:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0xfc000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L);
      case 89:
      case 121:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(4, 7);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa6_0(active0, 0xfc000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x800L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x2008000L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x88000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x5000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x800L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x2008000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000L);
      case 69:
      case 101:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(7, 15);
         return jjMoveStringLiteralDfa8_0(active0, 0x10800000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x24000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa8_0(active0, 0x800L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x2004000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000L);
      case 83:
      case 115:
         if ((active0 & 0x800000L) != 0L)
            return jjStopAtPos(8, 23);
         return jjMoveStringLiteralDfa9_0(active0, 0x800L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000000L);
      case 72:
      case 104:
         if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(9, 31);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x40000800L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa10_0(active0, 0x10000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa11_0(active0, 0x4000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa11_0(active0, 0x800L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa11_0(active0, 0x2000000L);
      case 78:
      case 110:
         if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(10, 14);
         return jjMoveStringLiteralDfa11_0(active0, 0x40000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa11_0(active0, 0x10000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa11_0(active0, 0x9000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa12_0(active0, 0x6000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa12_0(active0, 0x10000000L);
      case 71:
      case 103:
         if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(11, 30);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x800L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa12_0(active0, 0x1000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0x28000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa13_0(active0, 0x10000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa13_0(active0, 0x1000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x28000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa13_0(active0, 0x800L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa13_0(active0, 0x4000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa13_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
static private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa14_0(active0, 0x10000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa14_0(active0, 0x4000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa14_0(active0, 0x800L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa14_0(active0, 0x8000000L);
      case 83:
      case 115:
         if ((active0 & 0x1000000L) != 0L)
            return jjStopAtPos(13, 24);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa14_0(active0, 0x20000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa14_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
static private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa15_0(active0, 0x4000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa15_0(active0, 0x20000000L);
      case 78:
      case 110:
         if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(14, 27);
         break;
      case 82:
      case 114:
         return jjMoveStringLiteralDfa15_0(active0, 0x2000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa15_0(active0, 0x10000800L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
static private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa16_0(active0, 0x2000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa16_0(active0, 0x10000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa16_0(active0, 0x20000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa16_0(active0, 0x4000000L);
      case 89:
      case 121:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(15, 11);
         break;
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
static private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa17_0(active0, 0x4000000L);
      case 78:
      case 110:
         if ((active0 & 0x20000000L) != 0L)
            return jjStopAtPos(16, 29);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa17_0(active0, 0x10000000L);
      case 83:
      case 115:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(16, 25);
         break;
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
static private int jjMoveStringLiteralDfa17_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0);
      return 17;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa18_0(active0, 0x4000000L);
      case 78:
      case 110:
         if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(17, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(16, active0);
}
static private int jjMoveStringLiteralDfa18_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0);
      return 18;
   }
   switch(curChar)
   {
      case 78:
      case 110:
         return jjMoveStringLiteralDfa19_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(17, active0);
}
static private int jjMoveStringLiteralDfa19_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0);
      return 19;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa20_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(18, active0);
}
static private int jjMoveStringLiteralDfa20_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(18, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(19, active0);
      return 20;
   }
   switch(curChar)
   {
      case 82:
      case 114:
         return jjMoveStringLiteralDfa21_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(19, active0);
}
static private int jjMoveStringLiteralDfa21_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(19, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(20, active0);
      return 21;
   }
   switch(curChar)
   {
      case 73:
      case 105:
         return jjMoveStringLiteralDfa22_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(20, active0);
}
static private int jjMoveStringLiteralDfa22_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(20, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(21, active0);
      return 22;
   }
   switch(curChar)
   {
      case 79:
      case 111:
         if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(22, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(21, active0);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 29;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 20)
                        kind = 20;
                     jjCheckNAddTwoStates(16, 13);
                  }
                  else if (curChar == 47)
                     jjAddStates(0, 1);
                  else if (curChar == 48)
                  {
                     if (kind > 20)
                        kind = 20;
                     jjCheckNAdd(13);
                  }
                  else if (curChar == 40)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 4:
                  if (curChar == 40)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if (curChar == 41 && kind > 16)
                     kind = 16;
                  break;
               case 8:
                  if (curChar == 40)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 41)
                     jjAddStates(2, 3);
                  break;
               case 12:
                  if (curChar != 48)
                     break;
                  if (kind > 20)
                     kind = 20;
                  jjCheckNAdd(13);
                  break;
               case 13:
                  if (curChar == 46)
                     jjCheckNAdd(14);
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 20)
                     kind = 20;
                  jjCheckNAdd(14);
                  break;
               case 15:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 20)
                     kind = 20;
                  jjCheckNAddTwoStates(16, 13);
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 20)
                     kind = 20;
                  jjCheckNAddTwoStates(16, 13);
                  break;
               case 17:
                  if (curChar == 47)
                     jjAddStates(0, 1);
                  break;
               case 18:
                  if (curChar == 47)
                     jjCheckNAddStates(4, 6);
                  break;
               case 19:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(4, 6);
                  break;
               case 20:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 21:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 22:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(24, 25);
                  break;
               case 24:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(24, 25);
                  break;
               case 25:
                  if (curChar == 42)
                     jjAddStates(7, 8);
                  break;
               case 26:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(27, 25);
                  break;
               case 27:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(27, 25);
                  break;
               case 28:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x300000003000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if ((0x4100000041000L & l) != 0L)
                     jjAddStates(2, 3);
                  break;
               case 2:
                  if ((0x300000003000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
                  if ((0x4100000041000L & l) != 0L && kind > 16)
                     kind = 16;
                  break;
               case 5:
                  if ((0x300000003000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
                  if ((0x4100000041000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if ((0x300000003000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
                  if ((0x4100000041000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 19:
                  jjAddStates(4, 6);
                  break;
               case 24:
                  jjCheckNAddTwoStates(24, 25);
                  break;
               case 26:
               case 27:
                  jjCheckNAddTwoStates(27, 25);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 19:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(4, 6);
                  break;
               case 24:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(24, 25);
                  break;
               case 26:
               case 27:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(27, 25);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 29 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   18, 23, 2, 4, 19, 20, 22, 26, 28, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, "\73", null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, "\54", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x1ffd3ff81L, 
};
static final long[] jjtoSkip = {
   0x7eL, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[29];
static private final int[] jjstateSet = new int[58];
static protected char curChar;
/** Constructor. */
public ParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public ParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 29; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
